### ISSUE TITLE
已查过，网页上的id都没有问题

### ISSUE THREAD

**Issue by youthliuxi** [ETCartman/Class_Npels#7]
Traceback (most recent call last):
  File "run.py", line 6, in <module>
    a = Npels(username, pwd)
  File "K:\python\Class_Npels\Class_Npels.py", line 31, in __init__
    self.login()
  File "K:\python\Class_Npels\Class_Npels.py", line 41, in login
    self.driver.find_element_by_id("tbName").send_keys(self.username)
  File "D:\Anaconda3\envs\class\lib\site-packages\selenium\webdriver\remote\webelement.py", line 352, in send_keys
    'value': keys_to_typing(value)})
  File "D:\Anaconda3\envs\class\lib\site-packages\selenium\webdriver\remote\webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "D:\Anaconda3\envs\class\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "D:\Anaconda3\envs\class\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=69.0.3497.100)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 10.0.17134 x86_64)

**Comment by badbubble** [comment]
selenium好像更新了吧你可以检测一下相应的语法，我记得老师说过学校不会再用这个英语系统了。。。

**Comment by ghost** [comment]
> selenium好像更新了吧你可以检测一下相应的语法，我记得老师说过学校不会再用这个英语系统了。。。

大佬  求助！我也出现同样的问题。。。怎么解决？

**Comment by ghost** [comment]
![QQ截图20200105165610](https://user-images.githubusercontent.com/53423539/71777548-73c7b580-2fdc-11ea-94e0-5f4fffebe68d.jpg)

**Comment by badbubble** [comment]
@Sladewide 这个东西学校不是不用了吗...，要是还在用我假期就重新写一下吧。
